routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController');

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

Route::resource('bids','Backend\ProductController');

app/Order.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	public function user()
	{
		return $this->belongsTo('App\User');
	}

	public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i');
    }
}

app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Mail\Frontend\Contact\SendContact;
use App\Http\Requests\Frontend\Contact\SendContactRequest;

/**
 * Class ContactController.
 */
class ContactController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('frontend.contact');
    }

    /**
     * @param SendContactRequest $request
     *
     * @return mixed
     */
    public function send(SendContactRequest $request)
    {
        Mail::send(new SendContact($request));

        return redirect()->back()->withFlashSuccess(__('alerts.frontend.contact.sent'));
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Product;
use App\Cart;
use Auth;
use App\Http\Requests\ProductRequest;
use App\Order;
use Illuminate\Http\Request;
use Session;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Log;

/**
 * Class HomeController.
 */
class HomeController extends Controller
{
	/**
	 * @return \Illuminate\View\View
	 */
	public function index()
	{
		//return view('frontend.index');
		//$products = Product::all();
		
		return view('frontend.index');//->with('products', $products);
	}
	
	/**
	 * Get all information about product and send it to product page.
	 *
	 * @param string $category
	 * @param integer $id
	 * @return Response
	 */
	public function show($category, $id)
	{
		$product = Product::findOrFail($id);
		
		return view('frontend.main.productDescription')->with('product', $product);
		
	}
	
	/**
	 * Show the page with given category.
	 *
	 * @param string $category
	 * @return $Response
	 */
	public function showCategory($category)
	{
		$products = Product::where('category', $category)->get();
		if (Auth::check()) {
			$user = auth()->user();
			return view('frontend.main.showCategory')->with([
				'user' => $user->find(auth()->user()->id),
				'products' => $products
			]);
		} else {
			return view('frontend.main.showCategory')->with('products', $products);
		}
		
		//$user = find(auth()->user()->first());
		
	}
	
	/**
	 * Show the create product page.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function create()
	{
		return view('frontend.main.createProduct');
	}
	
	/**
	 * Handle information about new product and store it.
	 *
	 * @param ProductRequest $request
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function store(ProductRequest $request)
	{
		$name = mb_convert_case(trim($request->name), MB_CASE_TITLE);
		$imageName = str_random(12) . '.' . $request->file('image')->getClientOriginalExtension();
		$pathToImages = public_path('images/');
		
		$request->file('image')->move($pathToImages, $imageName);
		
		if ($request->diameter == '') {
			$request->diameter = NULL;
		}
		$data = [
			'category' => $request->category,
			'name' => $name,
			'price' => $request->price,
			'weight' => $request->weight,
			'diameter' => $request->diameter,
			'pathToImage' => 'images/' . $imageName,
			'composition' => $request->composition,
			'description' => $request->description,
			'article' => $request->article,
		];
		
		Product::create($data);
		
		return redirect('/')->with('success_message', 'Товар был успешно добавлен!');
	}
	
	/**
	 * Find and add choosen product to cart.
	 * @param Request $request
	 * @param Product $product
	 * @return \Illuminate\Http\JsonResponse
	 * @throws \Throwable
	 */
	public function addToCart(Request $request, Product $product)
	{
		$product = $product->find($request->productId);
		$oldCart = Session::has('cart') ? Session::get('cart') : null; // check if we already got cart in session
		$cart = new Cart($oldCart);
		$cart->addToCart($product, $product->id);
		Session::put('cart', $cart);
		
		$returnHTML = view('frontend.cart.cart')->render();
		return response()->json([
			'success' => 'Успех',
			'html' => $returnHTML
		]);
	}
	
	/**
	 * @param Request $request
	 * @return \Illuminate\Http\JsonResponse
	 * @throws \Throwable
	 */
	public function deleteFromCart(Request $request)
	{
		$oldCart = Session::get('cart');
		$cart = new Cart($oldCart);
		$cart->deleteFromCart($request->productId);
		
		if (empty($cart->items)) {
			Session::forget('cart');
		} else {
			Session::put('cart', $cart);
		}
		
		$returnHTML = view('frontend.cart.cart')->render();
		return response()->json([
			'success' => 'Элемент удалён',
			'html' => $returnHTML
		]);
	}
	
	/**
	 * @param Request $request
	 * @param Order $order
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function buyProducts(Request $request, Order $order)
	{
		$cart = Session::get('cart');
		
		Stripe::setApiKey('sk_test_WLRHLuQRqs7pJYIgOiOAVuHF');
		
		try {
			$charge = Charge::create([
				'amount' => round(($cart->totalPrice / 60), 2) * 100,
				'currency' => 'usd',
				'source' => $request['stripeToken'],
				'description' => 'Test Charge'
			]);
			
			$order->cart = serialize($cart);
			$order->address = $request['address'];
			$order->payment_id = $charge->id;
			auth()->user()->orders()->save($order);
		} catch (\Exception $error) {
			return redirect('/')->with('error', $error->getMessage());
		}
		
		Session::forget('cart');
		return redirect('/')->with('success_message', 'Покупка успешно завершена!');
		
	}
	
	/**
	 * @param Request $request
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function buyProducts2(Request $request)
	{
		$cart = $request->session()->get('cart');
		
		$collection = collect(collect($cart)->get('items'))->map(function ($item) {
			return collect($item)->except('price');
		});
		
		$arr["product"] = $collection->pluck('product')->toArray();
		$arr["product_kol"] = $collection->pluck('quantity')->toArray();
		
		$map = collect($arr)->map(function ($data, $id) {
			return collect($data)
				->keyBy(function ($item, $key) use ($id) {
					return "{$id}[{$key}]";
				});
		})
			->collapse()
			->merge(
				$request->only('street', 'home', 'pod', 'et', 'apart', 'phone', 'name', 'card', 'descr', 'person')
			);
		
		$obj = \FrontPad::new_order($map->all());
		$request->session()->flush();
		
		return redirect()->back()->with('success_message', 'Ваш заказ: ' . $obj->order_number);
		
		
	}
}

app/Http/Controllers/Frontend/PageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Guestbook;
use Illuminate\Http\Request;
use Image;
use Session;

class PageController extends Controller
{
    // /bonus_card
    public function bonus_card()
    {
        return view('frontend.bonus_card');
    }
	// /new_vacancy
	public function new_vacancy()
    {
        return view('frontend.new_vacancy');
    }
	// /conditions
	public function conditions()
    {
        return view('frontend.conditions');
    }
    //terms-use
    public function termsuse()
    {
        return view('frontend.terms-use');
    }
	// /guestbook
	public function guestbook()
    {
        return view('frontend.guestbook');
    }
    public function guestbooks()
    {
        if (Auth::check()) {
            $iduser = auth()->user()->id;
            if ($iduser == 1){
                $book = Guestbook::paginate(20);
                return view('frontend.admin.guestbooks', ['guestbooks' => $book]);
            }

        } else {
            return Response::view('frontend.errors.503', array(), 404);
        }

    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function addguestbook(Request $request)
    {
        //$user = auth()->user();

        $this->validate($request, ['foto' => 'image']);
        $imageName = 'default.png';
        if($request->hasFile('foto')) {
            $foto = $request->file('foto');
            $imageName = str_random(12) . '.' . $foto->getClientOriginalExtension();
            Image::make($foto)->save(public_path('images/guestbook/foto/' . $imageName)); //fit(400, 400)->

            //$user->update(['foto' => $imageName]);
        }

        $data = [
            'name' => $request->name,
            'number' => $request->number,
            'phone' => $request->phone,
            'comment' => $request->comment,
            'foto' => $imageName,
            'checkbox_mail' => $request->checkbox_mail,
            'checkbox_phone' => $request->checkbox_phone,
        ];

        Guestbook::create($data);

        return redirect('guestbook')->with('success_message', 'Отзыв успешно отправлен!');
        //dd($request);
        //return view('guestbook');
    }
}

app/Http/Controllers/Frontend/User/AccountController.php
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;

/**
 * Class AccountController.
 */
class AccountController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('frontend.user.account');
    }
}

app/Http/Controllers/Frontend/User/DashboardController.php
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('frontend.user.dashboard');
    }
}

app/Http/Controllers/Frontend/User/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;
use App\Repositories\Frontend\Auth\UserRepository;
use App\Http\Requests\Frontend\User\UpdateProfileRequest;

/**
 * Class ProfileController.
 */
class ProfileController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $userRepository;

    /**
     * ProfileController constructor.
     *
     * @param UserRepository $userRepository
     */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * @param UpdateProfileRequest $request
     *
     * @return mixed
     */
    public function update(UpdateProfileRequest $request)
    {
        $output = $this->userRepository->update(
            $request->user()->id,
            $request->only('first_name', 'last_name', 'email', 'avatar_type', 'avatar_location', 'timezone'),
            $request->has('avatar_location') ? $request->file('avatar_location') : false
        );

        // E-mail address was updated, user has to reconfirm
        if (is_array($output) && $output['email_changed']) {
            auth()->logout();

            return redirect()->route('frontend.auth.login')->withFlashInfo(__('strings.frontend.user.email_changed_notice'));
        }

        return redirect()->route('frontend.user.account')->withFlashSuccess(__('strings.frontend.user.profile_updated'));
    }
}

resources/views/frontend/user/account.blade.php
@extends('frontend.layouts.app')

@section('content')
    <div class="row justify-content-center align-items-center mb-3">
        <div class="col col-sm-10 align-self-center">
            <div class="card">
                <div class="card-header">
                    <strong>
                        {{ __('navs.frontend.user.account') }}
                    </strong>
                </div>

                <div class="card-body">
                    <div role="tabpanel">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a href="#profile" class="nav-link active" aria-controls="profile" role="tab" data-toggle="tab">{{ __('navs.frontend.user.profile') }}</a>
                            </li>

                            <li class="nav-item">
                                <a href="#edit" class="nav-link" aria-controls="edit" role="tab" data-toggle="tab">{{ __('labels.frontend.user.profile.update_information') }}</a>
                            </li>

                            @if ($logged_in_user->canChangePassword())
                            <li class="nav-item">
                                <a href="#password" class="nav-link" aria-controls="password" role="tab" data-toggle="tab">{{ __('navs.frontend.user.change_password') }}</a>
                            </li>
                            @endif
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade show active pt-3" id="profile" aria-labelledby="profile-tab">
                                @include('frontend.user.account.tabs.profile')
                            </div><!--tab panel profile-->

                            <div role="tabpanel" class="tab-pane fade show pt-3" id="edit" aria-labelledby="edit-tab">
                                @include('frontend.user.account.tabs.edit')
                            </div><!--tab panel profile-->

                            @if ($logged_in_user->canChangePassword())
                                <div role="tabpanel" class="tab-pane fade show pt-3" id="password" aria-labelledby="password-tab">
                                    @include('frontend.user.account.tabs.change-password')
                                </div><!--tab panel change password-->
                            @endif
                        </div><!--tab content-->
                    </div><!--tab panel-->
                </div><!--card body-->
            </div><!-- card -->
        </div><!-- col-xs-12 -->
    </div><!-- row -->
@endsection

resources/views/frontend/user/dashboard.blade.php
@extends('frontend.layouts.app')

@section('content')
    <div class="row mb-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <strong>
                        <i class="fa fa-dashboard"></i> {{ __('navs.frontend.dashboard') }}
                    </strong>
                </div><!--card-header-->

                <div class="card-body">
                    <div class="row">
                        <div class="col col-sm-4 order-1 order-sm-2  mb-4">
                            <div class="card mb-4 bg-light">
                                <img class="card-img-top" src="{{ $logged_in_user->picture }}" alt="Profile Picture">

                                <div class="card-body">
                                    <h4 class="card-title">
                                        {{ $logged_in_user->name }}<br/>
                                    </h4>

                                    <p class="card-text">
                                        <small>
                                            <i class="fa fa-envelope-o"></i> {{ $logged_in_user->email }}<br/>
                                            <i class="fa fa-calendar-check-o"></i> {{ __('strings.frontend.general.joined') }} {{ $logged_in_user->created_at->timezone(get_user_timezone())->format('F jS, Y') }}
                                        </small>
                                    </p>

                                    <p class="card-text">

                                        <a href="{{ route('frontend.user.account')}}" class="btn btn-info btn-sm mb-1">
                                            <i class="fa fa-user-circle-o"></i> {{ __('navs.frontend.user.account') }}
                                        </a>

                                        @can('view backend')
                                            &nbsp;<a href="{{ route ('admin.dashboard')}}" class="btn btn-danger btn-sm mb-1">
                                                <i class="fa fa-user-secret"></i> {{ __('navs.frontend.user.administration') }}
                                            </a>
                                        @endcan
                                    </p>
                                </div>
                            </div>

                            <div class="card mb-4">
                                <div class="card-header">Header</div>
                                <div class="card-body">
                                    <h4 class="card-title">Info card title</h4>
                                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                            </div><!--card-->
                        </div><!--col-md-4-->

                        <div class="col-md-8 order-2 order-sm-1">
                            <div class="row">
                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->
                            </div><!--row-->

                            <div class="row">
                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->
                            </div><!--row-->

                            <div class="row">
                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->

                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->

                                <div class="w-100"></div>

                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->

                                <div class="col">
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            Item
                                        </div><!--card-header-->

                                        <div class="card-body">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non qui facilis deleniti expedita fuga ipsum numquam aperiam itaque cum maxime.
                                        </div><!--card-body-->
                                    </div><!--card-->
                                </div><!--col-md-6-->
                            </div><!--row-->
                        </div><!--col-md-8-->
                    </div><!-- row -->
                </div> <!-- card-body -->
            </div><!-- card -->
        </div><!-- row -->
    </div><!-- row -->
@endsection

resources/views/frontend/user/profile.blade.php
@extends('layouts.app')

@section('title', 'Профиль')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="tabs">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-profile" data-toggle="tab"><i class="fa fa-user fa-btn"></i>&nbsp;Мой профиль</a></li>
                        <li><a href="#tab-order-story" data-toggle="tab"><i class="fa fa-cart-arrow-down fa-btn"></i>&nbsp;История заказов</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab-profile">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <h2 class="panel-title">Ваши данные</h2>
                                </div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-3" align="center">
                                            <img src="{{ asset('/images/uploads/avatars') }}/{{ $user->avatar }}" id="profile-avatar">
                                            <a href="" id="change-avatar-btn" class="btn btn-warning"><i class="fa fa-camera"></i>&nbsp;Изменить аватар</a>
                                        </div>
                                        <div class="col-md-9 ">
                                            <table class="table">
                                                <tbody>
                                                <tr>
                                                    <td>Ваше имя:</td>
                                                    <td>{{ $user->name }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Ваш телефон:</td>
                                                    <td>{{ $user->phone_number }}</td>
                                                </tr>
                                                <tr>
                                                    <td>E-mail:</td>
                                                    <td>{{ $user->email }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Пароль:</td>
                                                    <td><a href="" data-toggle="modal" data-target="#edit-password-modal">Изменить пароль</a></td>
                                                </tr>
                                                <tr>
                                                    <td>Улица:</td>
                                                    <td>{{ $user->street }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Дом:</td>
                                                    <td>{{ $user->home }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Квартира:</td>
                                                    <td>{{ $user->apart }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Подъезд:</td>
                                                    <td>{{ $user->pod }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Этаж:</td>
                                                    <td>{{ $user->et }}</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <form action="/user/profile/update_avatar" method="post" enctype="multipart/form-data" id="avatar-upload-form">
                                                <div class="input-group" id="avatar-upload">
                                                    <label class="input-group-btn">
                                                    <span class="btn btn-primary">
                                                        Browse&hellip; <input type="file" style="display: none;" multiple name="avatar">
                                                    </span>
                                                    </label>
                                                    <input type="text" class="form-control" id="image-name" readonly>
                                                </div>
                                                <button class="btn btn-login" id="form-upload-btn">Загрузить</button>
                                                {{ csrf_field() }}
                                            </form>
                                            <a href="" data-toggle="modal" data-target="#edit-profile-modal" class="btn btn-warning pull-right"><i class="fa fa-pencil"></i> Редактировать</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="alert alert-dismissable alert-danger" id="error-label">
                                <p class="text-center" id="error-text"></p>
                            </div>
                            @if (Session::has('success_message'))
                                <div class="alert alert-dismissable alert-success">
                                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                                    <p class="text-center">{{ Session::get('success_message') }}</p>
                                </div>
                            @endif
                        </div>
                        <div class="tab-pane fade in" id="tab-order-story">
                            <div class="panel panel-info">
                                <div class="panel-heading">История заказов</div>
                                <div class="panel-body">
                                    @if($user->orders)
                                        @foreach($orders as $order)
                                            <div class="panel panel-primary">
                                                <div class="panel-body">
                                                    <ul class="list-group">
                                                    @foreach($order->cart->items as $item)
                                                        <li class="list-group-item">
                                                            <span class="badge">{{ $item['price'] }} руб.</span>
                                                            {{ $item['item']['name'] }} || {{ $item['quantity'] }} шт.
                                                        </li>
                                                    @endforeach
                                                    </ul>
                                                </div>
                                                <div class="panel-footer">
                                                    <strong>Сумма: {{ $order->cart->totalPrice }} руб.</strong> ||
                                                    <strong>Адрес доставки: {{ $order->address }}</strong>
                                                    <strong class="pull-right">
                                                        Дата заказа: {{ $order->created_at }}
                                                    </strong>
                                                </div>
                                            </div>
                                        @endforeach
                                    @else
                                        <h2><span class="label label-primary center-block">ПОКА ПУСТО</span></h2>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('modals.editProfileModal')
    @include('modals.editPasswordModal')
@endsection